config/routes.rb
Rails.application.routes.draw do
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: %i[show edit update destroy]
  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    redirect_to flat_path(@flat)
  end

  def edit
  end

  def update
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :price_per_night, :number_of_guests)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_flat.html.erb
<div class="container m-3">
  <h1> <%= @flat.name %> </h1>
</div>

app/views/flats/index.html.erb
<nav class="navbar navbar-light bg-light px-3">
  <%= link_to "Simple AirBnb", flats_path, class:"navbar-brand flex-grow-1" %>
  <form class="d-flex">
      <input class="form-control" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success ms-2" type="submit">Search</button>
  </form>
  <%= link_to "Add flat", flats_path, class:"btn btn-outline-primary ms-2" %>
</nav>

<div class="container mt-3 p-4">
  <h1>All Our Flats</h1>
  <p>All <%= @flats.count %> flats</p>

  <div class="cards">
  <div class="row">
    <% @flats.each do |flat| %>
    <div class="card-category cold-md-4">
      <div class="card-description d-flex flex-column align-items-start">
              <h4 class="card-title mt-4"><%= flat.name %></h4>
              <p class="card-text mb-2"><%= flat.address %></p>
              <div class="card-details d-flex justify-content-start mt-2">
                  <p class="me-4"><i class="fa-solid fa-users"></i> <%= flat.number_of_guests %></p>
                  <p><i class="fa-solid fa-euro-sign"></i> <%= flat.price_per_night %></p>
              </div>
            </div>
            <div class="card-links d-flex justify-content-start border-top pt-3">
              <%= link_to "More info", flat_path(flat), class:"me-2 link-primary"  %>
              <%= link_to "Edit", edit_flat_path(flat), class:"me-2 link-warning" %>
              <%= link_to "Remove", flat_path(flat),
              data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
              class: "link-danger" %>
            </div>
    </div>
    <% end %>
  </div>
</div>

</div>

app/views/flats/show.html.erb
<%= render 'flat', flat: @flat %>

app/views/flats/test.html.erb
<div class="cards d-flex justify-content-evenly flex-wrap">
    <div class="row">
      <% @flats.each do |flat| %>
        <div class="card col-md-4 p-4">
            <img src="https://picsum.photos/300/200" alt="Picture of the flat" class="rounded">
            <div class="card-description d-flex flex-column align-items-start">
              <h4 class="card-title mt-4"><%= flat.name %></h4>
              <p class="card-text mb-2"><%= flat.address %></p>
              <div class="card-details d-flex justify-content-start mt-2">
                  <p class="me-4"><i class="fa-solid fa-users"></i> <%= flat.number_of_guests %></p>
                  <p><i class="fa-solid fa-euro-sign"></i> <%= flat.price_per_night %></p>
              </div>
            </div>
            <div class="card-links d-flex justify-content-start border-top pt-3">
              <%= link_to "More info", flat_path(flat), class:"me-2 link-primary"  %>
              <%= link_to "Edit", edit_flat_path(flat), class:"me-2 link-warning" %>
              <%= link_to "Remove", flat_path(flat),
              data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
              class: "link-danger" %>
            </div>
        </div>
      <% end %>
    </div-row>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>